language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: CB+SRO6zcDgBmMQ7nUx+HbhSOzTKKjT1/c530tIeP5JOqX/0iY+3U9bvTPuFJxS+pOacEQEg6r2VqQ1y4Qg3+7guNcJJc5PpYJMnix1czu1U9s2YU6/8VUyG4s8gooQiONor9vcfY6+W8J78fUDrQtSR5DFkqDeKlkM0ru2Qhy97c+CJrKpKGNwb53nZrSP6uhwNNpcJaltBmkz0KksZUxq2vlWMsj044HcTvhPehN6qzoX/pEKiYhYiVaVn/5uwoLqqA89QgtciirpngVdcz/9AE+u1etNoqFprZpCjlXiSV7Sv2KYBYaIKzC+4/4HF6xEeaDV6HZ0qoYvjqRpBfNlfn4mqLn85DgU+9trk6t6lHeKCdT3QCSXvyN67c2+7fMdM4ucnbN/fEeEvtrSYHav6FcnhoXs68qpQ2CGeNx0Hrfe+Kgd/NOZQmS2ysieWwR8Wu/ZuaVs8nxW6r6I0qqLu5sLV6axQJPAxL7NBgu5i0UJDSvzz0HO+Sgx/2TrbEjhISpxEuGs+XncMpmcIKHFw5SvfpJatCcAICsmjYckPD1Zv5xw601Ugj9LUrIPd4/jiaHsR9HxQDWgIZM38I7xtX9RWa+0BM/nlEoSulrU9SQkyYdvD4Ee6cT4ftpTUT7u46TsymtlMlX/7FRbFjesnxAHI0UaOdHR0qQ2yutw=
  app: skeleton-java-marius-cirstea